#!/bin/sh

include /lib/network

. /lib/functions.sh
. /lib/functions/network.sh
. /usr/share/libubox/jshn.sh
. /lib/netifd/netifd-proto.sh

get_iface_gateway() {
	local iface="$1"
	local var="$2"
	gwstr=`ubus call network.interface.$iface status | grep -A2 '"target": "::"' | grep '"nexthop": '`
	gwstr=${gwstr##*: \"}
	gwstr=${gwstr%%\"}
	
	eval "export -- \"$var=$gwstr\""
}

get_iface_l3_device() {
	local iface="$1"
	local var="$2"
	ifstr=`ubus call network.interface.$iface status | grep '"l3_device": '`
	ifstr=${ifstr##*: \"}
	ifstr=${ifstr%%\",}
	
	eval "export -- \"$var=$ifstr\""
}

get_gw_route_gateway() {
	local gw_route=`ip -6 route|grep default`
	local var="$1"
			
	[ -n "$gw_route" ] && {
		local oIFS="$IFS";IFS=" "; set -- $gw_route;IFS="oIFS"
		eval "export -- \"$var=$3\""
	}
}

get_gw_route_dev () {
	local gw_route=`ip -6 route|grep default`
	local var="$1"
	
	[ -n "$gw_route" ] && {
		local oIFS="$IFS";IFS=" "; set -- $gw_route;IFS="oIFS"
		eval "export -- \"$var=$5\""
	}
}

#setup_wanv6_gateway() {
#	local gateway ifname old_gw gw_dev proto device
#	
#	config_load /etc/config/network
#	config_get proto wanv6 proto
#	config_get device wanv6 ifname
#
#	get_gw_route_gateway old_gw	
#	get_gw_route_dev gw_dev
#	get_iface_l3_device wanv6 ifname
#	get_iface_gateway wanv6 gateway
#	
#	[ "$old_gw" == "$gateway" -a  "$ifname" == "$gw_dev" ] && return
#	
#	[ -n "$gateway" -a -n "$ifname" ] && {
#		ip -6 route del "::/0" dev "$gw_dev"
#		[ "$proto" == "6to4" ] && {
#			[ -n "$device" ] || device="eth0"
#			ip -6 route del "::/96" dev "$device"
#			ip -6 route add "::/96" dev "$ifname" metric 256
#		}
#		ip -6 route add "::/0" via "$gateway" dev "$ifname"
#	}
#}
setup_wanv6_gateway(){
	local ifname
	local gateway
	local gw_route
	config_load /etc/config/network
	config_get proto wanv6 proto
	config_get ifname wanv6 ifname
	gw_route=$(ip -6 route|grep default)
	[ -z ${gw_route} ] && {
		[ "$proto" == "dhcp6c" ] && {
			gateway=$(cat /proc/sys/net/ipv6/conf/$ifname/default_gateway)
			[ ${#gateway} -ne 0 ] && ip -6 route add "::/0" via "$gateway" dev "$ifname"
		}
	}
}

[ "$ACTION" == "ifup" -a "$INTERFACE" == "wanv6" ] && {
    local proto
    local ip_mode
    local prefix
	local lan_proto

    config_load /etc/config/network
    config_get proto wanv6 proto
    config_get ip_mode wanv6 ip_mode
	config_get lan_proto lanv6 proto

    if [ "$proto" == "dhcp6c" ] || [ "$proto" == "pppoev6" ]; then
        if [ "$ip_mode" == "prefix" ]; then
            prefix=`cat /tmp/dhcp6c/prefix.info`
            if [ $? -ne 0 ]; then 
                exit 0
            fi
            uci set network.lanv6.prefix="$prefix" 
            if [ $? -eq 0 ]; then
                uci commit network
                uci set protocol.dhcp6s.prefix="$prefix"
                uci set protocol.slaac.prefix="$prefix"
                uci set protocol.rdnss.prefix="$prefix"
                uci commit protocol
            fi
        fi
    fi

    if [ "$lan_proto" == "ndp" ]; then
        if [ "$proto" == "static" ]; then
            config_get ip6addr wanv6 ip6addr 
            if [ -n "$ip6addr" ]; then
                lanv6_prefix=$(lua /lib/netifd/lanv6_genrate_ndp_prefix.lua $ip6addr)
                echo "$lanv6_prefix" > /tmp/dhcp6c/ndp_prefix
            else
                exit 0
            fi
        elif [ "$proto" == "dhcp6c" ] || [ "$proto" == "pppoev6" ]; then
            lanv6_prefix=`cat /tmp/dhcp6c/ndp_prefix`
            #if [ $? -ne 0 ]; then
            #    exit 0
            #fi
			[ -z $lanv6_prefix ] && exit 0
        else 
            echo "hotplug.d 01-ipv6 not set prefix info lan proto: $lan_proto wan proto: $proto"
        fi

        [ -n "$lanv6_prefix" ] && {
            echo "hotplug.d iface 01-ipv6 $lanv6_prefix" > /dev/console
            uci set network.lanv6.prefix="$lanv6_prefix"
            uci set protocol.ndp.prefix="$lanv6_prefix"
            uci commit network
            uci commit protocol
        }
    fi

	echo "1" > /proc/sys/net/ipv6/conf/all/forwarding 
	ubus call network.interface.lanv6 down
	sleep 1
	ubus call network.interface.lanv6 up

	setup_wanv6_gateway
}

[ "$ACTION" == "ifdown" -a "$INTERFACE" == "wanv6" ] && {
	local ifname
	get_gw_route_dev ifname
	[ -n "$ifname" ] && ip -6 route del "::/0" dev "$ifname"
	echo "0" > /proc/sys/net/ipv6/conf/all/forwarding 
}

