# Makefile for nvrammngr lib.
# This lib is needed for tplink firmware recovery function support.
#


obj-$(CONFIG_NVRAMMANAGER) += missing.o nm_api.o nm_fwup.o nm_lib.o sysProductInfo.o bigNumber.o shaAndSha512.o rsaVerify.o #fwrecovery_api.o fwrecovery_gpio.o
obj-$(CONFIG_NVRAMMANAGER_SPI) += nm_spi.o

