#!/bin/sh /etc/rc.common

START=99
STOP=90

USE_PROCD=1

ipv6_enable() {
    config_load network
    config_get ifname wan ifname

    config_load protocol
    config_get enable wanv6 enable

    case "$enable" in 
        on)
            # enable wan ipv6
            echo "0" > /proc/sys/net/ipv6/conf/$ifname/disable_ipv6
            ;;
        off)
            # disable wan ipv6
            echo "1" > /proc/sys/net/ipv6/conf/$ifname/disable_ipv6
            ;;
        *) 
            ;;
    esac
}

start_service() {
    ipv6_enable
    return 0
}

stop_service() {
    return 0
}

reload_service() {
    ipv6_enable
}

service_triggers() {
    procd_add_reload_trigger "protocol"
}
