# Makefile for nvrammngr lib.
# This lib is needed for tplink firmware recovery function support.
#

obj-$(CONFIG_UIP_HTTPD) += uip.o uip_arp.o uiplib.o psock.o timer.o uip-neighbor.o httpd.o http-strings.o httpd-fs.o httpd-cgi.o
